### ISSUE TITLE
Big Sur Download link

### ISSUE THREAD

**Issue by ashik4u** [VictorxD70/Hackintosh-OC-Dell-Inspiron-15-3567#1]
Where to download Big Sur file for Dell Inspiron 15 3567?

**Comment by VictorxD70** [comment]
EFI folder to use with BIg Sur Installation: https://github.com/VictorxD70/Hackintosh-OC-Dell-Inspiron-15-3567/releases/download/OpenCore-0.7.4/EFI.zip

**Comment by ashik4u** [comment]
I mean from where to download .raw file

**Comment by VictorxD70** [comment]
Oh, you can use one Olarila Image: https://www.olarila.com/topic/6278-hackintosh-olarila-vanilla-images/

**Comment by ashik4u** [comment]
> Oh, you can use one Olarila Image: https://www.olarila.com/topic/6278-hackintosh-olarila-vanilla-images/

Thank you. i was able to install Big Sur. But wifi and Bluetooth are not working. Any solution?

**Comment by VictorxD70** [comment]
Maybe your wifi/bluetooth adapter is different, this folder works with the Atheros adapter

**Comment by ashik4u** [comment]
![image](https://user-images.githubusercontent.com/6330712/136666783-0726c4a2-93e5-4425-9444-35cfc91b840e.png)
Here is mine. Please suggest me a solution

**Comment by VictorxD70** [comment]
On Windows press Win + R and type devmgmt.msc and press enter, open Network Adapters and send me a print

**Comment by ashik4u** [comment]
![image](https://user-images.githubusercontent.com/6330712/136667221-ec5984b9-7871-4302-8fec-d16c722b5e05.png)
Here it is

**Comment by VictorxD70** [comment]
[EFI.zip](https://github.com/VictorxD70/Hackintosh-OC-Dell-Inspiron-15-3567/files/7316040/EFI.zip)
Test this EFI folder, I put intel drivers and removed atheros

**Comment by ashik4u** [comment]
> [EFI.zip](https://github.com/VictorxD70/Hackintosh-OC-Dell-Inspiron-15-3567/files/7316040/EFI.zip)
> Test this EFI folder, I put intel drivers and removed atheros

I have already installed the MacOS. Should I overwrite it on MACOS or in EFI. I have no idea

**Comment by VictorxD70** [comment]
have you copied the EFI folder to your system's EFI partition? if not, you won't be able to start macOS without the pendrive. Boot your macOS, install this app to applications: https://github.com/headkaze/Hackintool/releases/download/3.6.2/Hackintool.zip
on hackintool go to Disks tab, and mount EFI partition like the image:
![InkedHackintool](https://user-images.githubusercontent.com/15053997/136668332-45a14285-b61d-4d9a-8139-dfeb92f42e98.jpg)
it will show you the EFI partition, open it, open the EFI folder, you will see some folders like: BOOT, Microsoft... paste here the BOOT and OC folders of the EFI file I sent you and restart

**Comment by ashik4u** [comment]
> have you copied the EFI folder to your system's EFI partition? if not, you won't be able to start macOS without the pendrive. Boot your macOS, install this app to applications: https://github.com/headkaze/Hackintool/releases/download/3.6.2/Hackintool.zip
> on hackintool go to Disks tab, and mount EFI partition like the image:
> ![InkedHackintool](https://user-images.githubusercontent.com/15053997/136668332-45a14285-b61d-4d9a-8139-dfeb92f42e98.jpg)
> it will show you the EFI partition, open it, open the EFI folder, you will see some folders like: BOOT, Microsoft... paste here the BOOT and OC folders of the EFI file I sent you and restart
> 

I did the same bro. Can boot now without Pendrive. But Wifi still not working.

**Comment by VictorxD70** [comment]
install this app on macOS and check if works: https://github.com/OpenIntelWireless/HeliPort/releases/download/v1.4.1/HeliPort.dmg

**Comment by VictorxD70** [comment]
make sure you have used this EFI folder:
[EFI.zip](https://github.com/VictorxD70/Hackintosh-OC-Dell-Inspiron-15-3567/files/7316128/EFI.zip)

**Comment by ashik4u** [comment]
> make sure you have used this EFI folder:
> [EFI.zip](https://github.com/VictorxD70/Hackintosh-OC-Dell-Inspiron-15-3567/files/7316128/EFI.zip)

Is there anything to do with clover? 🍀

**Comment by VictorxD70** [comment]
> > make sure you have used this EFI folder:
> > [EFI.zip](https://github.com/VictorxD70/Hackintosh-OC-Dell-Inspiron-15-3567/files/7316128/EFI.zip)
> 
> Is there anything to do with clover? 🍀

I tested Clover, but atheros wifi don't works on Clover, that's why I don't use.

**Comment by VictorxD70** [comment]
> install this app on macOS and check if works: https://github.com/OpenIntelWireless/HeliPort/releases/download/v1.4.1/HeliPort.dmg

you tested?

**Comment by ashik4u** [comment]
> > install this app on macOS and check if works: https://github.com/OpenIntelWireless/HeliPort/releases/download/v1.4.1/HeliPort.dmg
> 
> you tested?

Worked bro 😊😊
That Heliport software worked for me. ❤️❤️❤️

**Comment by VictorxD70** [comment]
> Worked bro 😊😊 That Heliport software worked for me. ❤️❤️❤️

you can set Heliport app to start with macOS: System Preferences > Users and Groups > Login Items, click in + and select Heliport!

**Comment by ashik4u** [comment]
> > Worked bro 😊😊 That Heliport software worked for me. ❤️❤️❤️
> 
> you can set Heliport app to start with macOS: System Preferences > Users and Groups > Login Items, click in + and select Heliport!

Thanks mate. If you want, you can close the issue. I want to change the theme of Boot Screen. If you have a guide, pls share. Take care.
Here is my telegram: @ashik4u
Discord: Ashik#9882
Website: digi-goods.co.uk

**Comment by VictorxD70** [comment]
> Thanks mate. If you want, you can close the issue. I want to change the theme of Boot Screen. If you have a guide, pls share. Take care. Here is my telegram: @ashik4u Discord: Ashik#9882 Website: digi-goods.co.uk

Np! You can use this guide: https://dortania.github.io/OpenCore-Post-Install/cosmetic/gui.html#setting-up-opencore-s-gui
On OpenCore folder: OC/Resources/Image, the theme is here.
