### ISSUE TITLE
Trying Install 

### ISSUE THREAD

**Issue by KhronosSam1996** [VictorxD70/Hackintosh-OC-Dell-Inspiron-15-3567#2]
Hi friend. Congratulations. 
May you Help me please?

This EFI Works Very well at my 3567. It has the same settings. But I am facing one trouble.

First I change with propertree the serial number, the board Serial and de UUID. After that, with a pendrive with the boot Olaria 11.1 Big Sur a change tha folder EFI to yours changed. 

I start the proccess, I erase the partition with the SSD to Journaling ( APFS doesnt work ). After that I make Install of Big Sur. If I format as APFS, at the First restart, the place where I am making install doesnt shows. Shows only the Big Sur instal to install once again. When in Journaling, It shows the place ( the SSD renamed macOS ), but at Last reestart to start the system, SSD dont show. May you Help me to install, please

**Comment by VictorxD70** [comment]
Hi, make sure you enabled ahci mode in SATA operation, in bios, and did you replace SSD EFI? , see if you notice any error messages in opencore, if possible send me screenshots of what is happening
