### ISSUE TITLE
Wifi and Bluetooth not working 

### ISSUE THREAD

**Issue by jndoser** [VictorxD70/Hackintosh-OC-Dell-Inspiron-15-3567#3]
Your EFI makes me surprised, everything works very well but except wifi and Bluetooth, i hope you will fix it soon, i am in Ventura.
Thank you

**Comment by VictorxD70** [comment]
Thanks! But I am not the developer of the Wifi and Bluetooth drivers, support for these drivers stopped in macOS Monterey version, so I disabled these drivers on my EFI for macOS Monterey or newer. Here is the support forum link for these drivers:
[IO80211Family modif](https://www.insanelymac.com/forum/files/file/1008-io80211family-modif/)

**Comment by jndoser** [comment]
> Thanks! But I am not the developer of the Wifi and Bluetooth drivers, support for these drivers stopped in macOS Monterey version, so I disabled these drivers on my EFI for macOS Monterey or newer. Here is the support forum link for these drivers: [IO80211Family modif](https://www.insanelymac.com/forum/files/file/1008-io80211family-modif/)

Thank you, but I tried to install Big Sur but the problem is the same, Bluetooth seems work but the wifi could not scan any network, I can turn on or off wifi but seems like it doesn't recognize any wifi network

**Comment by VictorxD70** [comment]
It looks like your Wifi and Bluetooth adapter is not the same as what I defined in the EFI specs, can you check what your Wfi and Bluetooth adapter is?

**Comment by jndoser** [comment]
> It looks like your Wifi and Bluetooth adapter is not the same as what I defined in the EFI specs, can you check what your Wfi and Bluetooth adapter is?

Yes, sure. I see in the device manager, my built in wifi is Intel(R) Dual Band Wireless-AC 3165 and the Bluetooth is Intel(R) Wireless Bluetooth(R). If it's what you want to know. Could you tell me how to get that information? Thanks

**Comment by VictorxD70** [comment]
Please test this EFI folder: [EFI.zip](https://drive.google.com/file/d/1xkjq3Rwd8ZtAHgnk7eqF_82D5hBnRBya/view?usp=share_link), I changed Wifi and Bluetooth drivers. After update your EFI folder, restart and install this app on mac: [HeliPort.dmg](https://github.com/OpenIntelWireless/HeliPort/releases/download/v1.5.0-alpha/HeliPort.dmg), use this app to manage your Wifi adaper.

**Comment by jndoser** [comment]
> Please test this EFI folder: [EFI.zip](https://drive.google.com/file/d/1xkjq3Rwd8ZtAHgnk7eqF_82D5hBnRBya/view?usp=share_link), I changed Wifi and Bluetooth drivers. After update your EFI folder, restart and install this app on mac: [HeliPort.dmg](https://github.com/OpenIntelWireless/HeliPort/releases/download/v1.5.0-alpha/HeliPort.dmg), use this app to manage your Wifi adaper.

Thanks for your works, the wifi works fine, the bluetooth could connect to another devices too, but it can't not turn off bluetooth. And I don't know why after sign in Apple Account, the system will restart accidentally but it doesn't signed in. And I wonder if I could use this EFI file for Ventura?

**Comment by VictorxD70** [comment]
> Thanks for your works, the wifi works fine, the bluetooth could connect to another devices too, but it can't not turn off bluetooth. And I don't know why after sign in Apple Account, the system will restart accidentally but it doesn't signed in. And I wonder if I could use this EFI file for Ventura?

Yes you can use this folder with Ventura. About the Apple account, I set generic serials in the EFI and you'ill need to change the serials (MLB, SystemSerialNumber & SystemUUID) in the SMBIOS with new ones for MacBookPro14,1 for correctly work with Apple servers, you can generate with: [GenSMBIOS](https://github.com/corpnewt/GenSMBIOS), if you need help to generate, I can generate new ones and email you the EFI folder.

**Comment by jndoser** [comment]
> > Thanks for your works, the wifi works fine, the bluetooth could connect to another devices too, but it can't not turn off bluetooth. And I don't know why after sign in Apple Account, the system will restart accidentally but it doesn't signed in. And I wonder if I could use this EFI file for Ventura?
> 
> Yes you can use this folder with Ventura. About the Apple account, I set generic serials in the EFI and you'ill need to change the serials (MLB, SystemSerialNumber & SystemUUID) in the SMBIOS with new ones for MacBookPro14,1 for correctly work with Apple servers, you can generate with: [GenSMBIOS](https://github.com/corpnewt/GenSMBIOS), if you need help to generate, I can generate new ones and email you the EFI folder.

Yes, please. i don't have any experience about this. It's nice if i could receive that EFI from you, you could put link here directly or send via email hoanglongdev533@gmail.com. Many thanks again. Btw, i think the built-in sound works fine both input and ouput  but if you try to plug a headphone, the micro will doesn't work although the output sound works fine. It's great if you could find the root cause then fix it. I had searched in many internet source but change the layout id doesn't fix that.

**Comment by VictorxD70** [comment]
> Yes, please. i don't have any experience about this. It's nice if i could receive that EFI from you, you could put link here directly or send via email [hoanglongdev533@gmail.com](mailto:hoanglongdev533@gmail.com). Many thanks again. Btw, i think the built-in sound works fine both input and ouput but if you try to plug a headphone, the micro will doesn't work although the output sound works fine. It's great if you could find the root cause then fix it. I had searched in many internet source but change the layout id doesn't fix that.

I sent the EFI folder with the new serials to your email. About the microphone, check if the mac changed the microphone when it was connected, and try to disable the ambient noise reduction, in the sound settings.

**Comment by jndoser** [comment]
> > Yes, please. i don't have any experience about this. It's nice if i could receive that EFI from you, you could put link here directly or send via email [hoanglongdev533@gmail.com](mailto:hoanglongdev533@gmail.com). Many thanks again. Btw, i think the built-in sound works fine both input and ouput but if you try to plug a headphone, the micro will doesn't work although the output sound works fine. It's great if you could find the root cause then fix it. I had searched in many internet source but change the layout id doesn't fix that.
> 
> I sent the EFI folder with the new serials to your email. About the microphone, check if the mac changed the microphone when it was connected, and try to disable the ambient noise reduction, in the sound settings.

Thanks for the file. I used it in Ventura but it doesn't work, touchpad, wifi, sound ... seems doesn't work. I will try it on BigSur then inform you later

Edit: Seems like I had booted to the wrong EFI partition, everything work fine on Ventura now but like I said the microphone doesn't work, idk why. I will try on the Big Sur later. Many thanks.
