### ISSUE TITLE
Wifi - QCA9565 / AR9565

### ISSUE THREAD

**Issue by maxmalato** [VictorxD70/Hackintosh-OC-Dell-Inspiron-15-3567#5]
Olá, tudo bem? 

Eu tenho um Dell das mesmas especificações e o meu Wi-Fi é um QCA9565 / AR9565. Eu testei várias EFIs que você publicou, mas até o momento nenhuma funciona 100% o Wi-Fi. Eu consigo conectar, mas quando realizo um teste de velocidade, não passa dos 3MB/s.

Já procurei em vários sites, blogs e fóruns e até o momento não encontrei uma solução.

Está faltando apenas essa configuração para que o meu Big Sur seja completo! Hehe

Se tiver alguma solução ou me dizer que realmente não dá, agradeço muito! 

Abraços meu amigo!

**Comment by VictorxD70** [comment]
Tudo bem,

Realmente o driver não funciona tão bem no Big Sir, já que ele é uma adaptação de um driver do High Sierra, por isso o sinal do Wi-Fi sempre aparece com um ponto, mas consigo pegar até 50MiB/s (cerca de 6MB/s), o que você pode fazer para melhorar é mudar algumas configurações no seu roteador, tente usar um canal próximo do 11, use o modo N, e nunca use a largura de banda de 40 MHz, use 20 MHz.

Espero ter ajudado!

**Comment by maxmalato** [comment]
Entendi!

O problema é que uso na empresa, então pra realizar essas configurações no roteador será mais complicado.

Sabe me dizer se existe alguma outra versão do macOS que possa funcionar normalmente? Por exemplo, o Catalina ou uma anterior?

**Comment by VictorxD70** [comment]
No Catalina tem mais compatibilidade, inclusive o problema do sinal estar em um ponto, lá não acontece, mas não posso te garantir melhor desempenho.

Eu te recomendo substituir esse adaptador por um BCM94360NG da Fenvi, ele é dual band e funciona nativamente até o macOS Ventura, esse adaptador funciona muito bem nesse notebook.

**Comment by maxmalato** [comment]
Entendi meu amigo.

Eu posso fazer um teste com o Catalina. Não lembro se usei a versão da EFI 0.9.4 ou 0.9.3 para o Catalina só que a imagem não carregou e sempre voltava para a tela do Open Core. Sabe me dizer a melhor versão da EFI para este sistema?

**Comment by VictorxD70** [comment]
Eu fiz um teste no Catalina 10.15.7 com a última versão da EFI, 0.9.5, e não tive esse problema, o macOS funcionou normalmente.

**Comment by maxmalato** [comment]
Meu amigo, essa versão do Catalina é não conseguir encontrar. Se tiver algum link para que eu possa realizar os testes. 

Eu encontrei apenas a versão 10.15.7

**Comment by maxmalato** [comment]
Meu amigo, eu fiz os testes aqui e deu certo para subir a imagem, mas infelizmente o sinal do Wi-Fi ficou fraco mesmo no Catalina. Agradeço demais pela ajuda. Realmente a melhor opção é comprar a placa de rede que tens sugeridos.

Abraços!!!
