### ISSUE TITLE
Configurações de Bios para o Inspiron 15 3567

### ISSUE THREAD

**Issue by Alfred-lms** [VictorxD70/Hackintosh-OC-Dell-Inspiron-15-3567#6]
Opa, tudo bem?

Cara tenho literalmente as mesmas especificações do seu teste, porém sempre que vou com a EFI, dou boot no opencore, porém nunca consigo fazer com que o opencore dê boot na imagem DMG, no que andei pesquisando o disco de recovery deveria aparecer com o nome do disco e um (dmg) após, porém não acontece comigo, e como em alguns casos temos outros nomes para certos parâmetros da bios (como Virtualization for Direct I/O ao invés do VT-d da intel) queria saber se você poderia adicionar algum tipo de informação relativa às configurações da BIOS para o inspiron 15 3567!

Grato!

**Comment by Alfred-lms** [comment]
Update, eu irei enviar alguns prints das minhas configs de bios, porém não foi necessário muito além de desativar o secure boot.

Entretanto no Config.plist eu desativei o Hideauxiliary, que estava em True para False, e dessa forma foi possível ver o formato DMG e entrar em boot.

Caso alguém mais tenha esse problema, essa foi minha solução!

**Comment by VictorxD70** [comment]
Oi, tudo bem?

Vou colocar sim as opções de BIOS recomendadas depois, quanto ao HideAuxiliary, é só apertar espaço para exibir a recuperação.

**Comment by Alfred-lms** [comment]
Acredita que quando aperto não aparece? fiz pela configuração no config.plist mesmo, de toda forma muito obrigado!
