### ISSUE TITLE
Can’t boot after initial install(?)

### ISSUE THREAD

**Issue by d-anez3** [VictorxD70/Hackintosh-OC-Dell-Inspiron-15-3567#7]
I’m new to Hackintoshing so I’m not sure if I’m exactly doing everything right but I managed to get into the USB in order to wipe my SSD and begin the install process.

After the installer said “12 minutes remaining” the screen went black and the computer restarted. I assume this meant the install finished but when the computer tried booting, it only managed to get into the Windows Boot Manager where it said it couldn’t start Windows (obviously). Now the only option available in the BIOS to boot into is the Windows Boot Manager.
![IMG_1601](https://github.com/VictorxD70/Hackintosh-OC-Dell-Inspiron-15-3567/assets/113142829/fd02b48a-8cfb-4581-88c0-21781cf6b3fd)
Initially it showed it along with my SSD but after setting my SSD as the primary boot partition and restarting, I landed back in the Windows Boot Manager and my SSD disappeared from the boot options.

Not sure where to go from here. I’m not 100% if my BIOS is set up correctly for this hardware, I just went with what I saw online.

**Comment by VictorxD70** [comment]
Apologies for the delay. 

You can add a new entry (the opencore one), in the "Add Boot Option", navigate to your EFI partition > EFI > Boot, and select "bootx64.efi", and define a name (it can be "OpenCore"), and put it up, save and try again.

**Comment by d-anez3** [comment]
I should’ve mentioned it in the original issue, but I did try doing that (and just tried it again right now). Even just having OpenCore enabled and not the Windows Boot Manager still sends me to Windows saying it couldn’t start.
![image](https://github.com/VictorxD70/Hackintosh-OC-Dell-Inspiron-15-3567/assets/113142829/3704a88c-5288-475c-b679-e3800a4d160f)

**Comment by VictorxD70** [comment]
This looks like the bootx64.efi that is in EFI > Boot is from Windows Boot Manager, you need to check your EFI partition, and replace it, or copy the OpenCore EFI folder again and replace.
