### ISSUE TITLE
HDMI only working with weird workaround

### ISSUE THREAD

**Issue by an0nd3v** [VictorxD70/Hackintosh-OC-Dell-Inspiron-15-3567#8]
Hi, so I'm using this EFI on my Inspiron 15-3567 on Ventura with mostly no issues except HDMI does not work normally. When I plug in the cable, nothing happens. The only way I've been able to get it working is a weird workaround- turning on the laptop with the cable plugged in and immediately closing the lid- which forces it to output to HDMI. The problem is it **only** outputs to HDMI and when I open the laptop lid nothing shows on the laptop screen, and the only way to get the screen on the laptop to work again is to reboot with the lid open. Is there any way to get HDMI working normally so I can have two screens at once?
I haven't modified the EFI at all except I replaced itlwm with Airportitlwm and removed the other WiFi kexts for Atheros to make boot time faster (which shouldn't have any effect on the display, I did not modify WhateverGreen)

**Comment by VictorxD70** [comment]
Hi, try removing and reconnecting the cable, sometimes the Mac doesn't pass an HDMI signal when it connects, as for removing the atheros kexts, it won't make it start faster on the Ventura, the atheros kexts are set to only start up to BigSur.

I tested the HDMI on my notebook, and it is working normally as you see below:

![Captura de Tela 2023-10-14 às 13 38 16](https://github.com/VictorxD70/Hackintosh-OC-Dell-Inspiron-15-3567/assets/15053997/11f6ac16-dbe4-4af0-8dd5-500ebf6f7374)

**Comment by an0nd3v** [comment]
Still nothing- I also tried adding -wegnoegpu to boot-args as some people say that worked but still nothing.
